
version: '3'

services:
  web-terminal:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
    command: python app.py
    container_name: macos-web-terminal
